# Generated by Django 5.1 on 2024-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_caja_total_final_alter_caja_total_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
