# Generated by Django 5.1 on 2024-09-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_caja_total_final_alter_caja_total_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_comanda',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
