# Generated by Django 5.1 on 2024-09-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_pedido_numero_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('servido', 'Servido'), ('pagado', 'Pagado'), ('eliminado', 'Eliminado')], default='pendiente', max_length=10),
        ),
    ]
